language: objective-c

before_script:
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout tags/0.4.2
  - ./autogen.sh
  - ./configure && make check -j3
  - sudo make install
  - cd ..
  - cd DeepEnd
  - git submodule init
  - git submodule update
  - cd ..

script:
  - xcodebuild -workspace Poison.xcworkspace -scheme Poison
  - xcodebuild -workspace Poison.xcworkspace -scheme Silica
  - xcodebuild -workspace Poison.xcworkspace -scheme Hibiki

notifications:
  irc:
    channels:
      - "chat.freenode.net#tox-dev"
    template: "%{repository} (%{commit}): %{message} Changes: %{compare_url}"
    on_success: always
    on_failure: always
